
import { ETF, PerformanceData } from './types';

const generateHistory = (base: number, volatility: number): PerformanceData[] => 
  Array.from({ length: 30 }, (_, i) => ({
    time: `Day ${i}`,
    value: base + (Math.random() - 0.5) * volatility * (i + 1)
  }));

export const TOP_ETFS: ETF[] = [
  {
    id: '1',
    ticker: 'VUSA',
    name: 'Vanguard S&P 500 UCITS ETF',
    type: 'Equity',
    provider: 'Vanguard',
    price: 94.20,
    change: 1.25,
    aum: '€34.2B',
    ter: 0.07,
    isin: 'IE00B3XXRP09',
    domicile: 'Ireland',
    replication: 'Physical (Full)',
    distribution: 'Distributing',
    riskScale: 6,
    holdings: [
      { name: 'Apple', weight: '7.1%', logo: 'https://logo.clearbit.com/apple.com' },
      { name: 'Microsoft', weight: '6.5%', logo: 'https://logo.clearbit.com/microsoft.com' },
      { name: 'Amazon', weight: '3.4%', logo: 'https://logo.clearbit.com/amazon.com' },
      { name: 'Nvidia', weight: '2.8%', logo: 'https://logo.clearbit.com/nvidia.com' },
      { name: 'Alphabet', weight: '2.1%', logo: 'https://logo.clearbit.com/google.com' },
    ],
    history: generateHistory(90, 2),
  },
  {
    id: '2',
    ticker: 'IWDA',
    name: 'iShares Core MSCI World UCITS',
    type: 'Global',
    provider: 'iShares',
    price: 82.15,
    change: -0.45,
    aum: '€55.2B',
    ter: 0.20,
    isin: 'IE00B4L5Y983',
    domicile: 'Ireland',
    replication: 'Physical (Sampling)',
    distribution: 'Accumulating',
    riskScale: 5,
    holdings: [
      { name: 'Apple', weight: '5.2%', logo: 'https://logo.clearbit.com/apple.com' },
      { name: 'Microsoft', weight: '4.8%', logo: 'https://logo.clearbit.com/microsoft.com' },
      { name: 'Amazon', weight: '2.1%', logo: 'https://logo.clearbit.com/amazon.com' },
      { name: 'Meta', weight: '1.5%', logo: 'https://logo.clearbit.com/meta.com' },
      { name: 'Tesla', weight: '1.2%', logo: 'https://logo.clearbit.com/tesla.com' },
    ],
    history: generateHistory(80, 1.5),
  },
  {
    id: '3',
    ticker: 'VWRL',
    name: 'Vanguard FTSE All-World UCITS',
    type: 'Global',
    provider: 'Vanguard',
    price: 112.40,
    change: 0.88,
    aum: '€12.1B',
    ter: 0.22,
    isin: 'IE00B3RBWM25',
    domicile: 'Ireland',
    replication: 'Physical (Full)',
    distribution: 'Distributing',
    riskScale: 5,
    holdings: [
      { name: 'Apple', weight: '4.1%', logo: 'https://logo.clearbit.com/apple.com' },
      { name: 'Microsoft', weight: '3.9%', logo: 'https://logo.clearbit.com/microsoft.com' },
      { name: 'TSMC', weight: '1.8%', logo: 'https://logo.clearbit.com/tsmc.com' },
    ],
    history: generateHistory(110, 1),
  },
  {
    id: '4',
    ticker: 'EGLN',
    name: 'iShares Physical Gold ETC',
    type: 'Gold',
    provider: 'iShares',
    price: 38.45,
    change: 2.15,
    aum: '€14.5B',
    ter: 0.12,
    isin: 'IE00B4ND3602',
    domicile: 'Ireland',
    replication: 'Physical',
    distribution: 'None',
    riskScale: 4,
    holdings: [
      { name: 'Gold Bullion', weight: '100%', logo: 'https://logo.clearbit.com/gold.org' },
    ],
    history: generateHistory(36, 0.5),
  },
  {
    id: '5',
    ticker: 'SXR8',
    name: 'iShares VII PLC - S&P 500 Acc',
    type: 'Equity',
    provider: 'iShares',
    price: 512.30,
    change: 1.34,
    aum: '€68.1B',
    ter: 0.07,
    isin: 'IE00B5BMR087',
    domicile: 'Ireland',
    replication: 'Physical (Full)',
    distribution: 'Accumulating',
    riskScale: 6,
    holdings: [
      { name: 'Apple', weight: '7.1%', logo: 'https://logo.clearbit.com/apple.com' },
    ],
    history: generateHistory(500, 5),
  },
  {
    id: '6',
    ticker: 'IUIT',
    name: 'iShares S&P 500 Info Tech UCITS',
    type: 'Tech',
    provider: 'iShares',
    price: 24.10,
    change: 2.55,
    aum: '€8.1B',
    ter: 0.15,
    isin: 'IE00B3WJKG14',
    domicile: 'Ireland',
    replication: 'Physical (Full)',
    distribution: 'Accumulating',
    riskScale: 7,
    holdings: [
      { name: 'Microsoft', weight: '22.1%', logo: 'https://logo.clearbit.com/microsoft.com' },
      { name: 'Apple', weight: '21.5%', logo: 'https://logo.clearbit.com/apple.com' },
      { name: 'Nvidia', weight: '14.8%', logo: 'https://logo.clearbit.com/nvidia.com' },
    ],
    history: generateHistory(20, 1.2),
  },
  {
    id: '7',
    ticker: 'IS3Q',
    name: 'iShares MSCI World Quality Factor',
    type: 'Equity',
    provider: 'iShares',
    price: 64.22,
    change: 0.12,
    aum: '€14.2B',
    ter: 0.30,
    isin: 'IE00BP3QZ825',
    domicile: 'Ireland',
    replication: 'Physical (Full)',
    distribution: 'Accumulating',
    riskScale: 5,
    holdings: [
      { name: 'ASML', weight: '3.2%', logo: 'https://logo.clearbit.com/asml.com' },
      { name: 'LVMH', weight: '2.8%', logo: 'https://logo.clearbit.com/lvmh.com' },
    ],
    history: generateHistory(62, 0.8),
  },
  {
    id: '8',
    ticker: 'QDVE',
    name: 'iShares S&P 500 Information Tech',
    type: 'Tech',
    provider: 'iShares',
    price: 28.50,
    change: 3.12,
    aum: '€5.4B',
    ter: 0.15,
    isin: 'IE00B3WJKG14',
    domicile: 'Ireland',
    replication: 'Physical (Full)',
    distribution: 'Accumulating',
    riskScale: 7,
    holdings: [
      { name: 'Nvidia', weight: '18%', logo: 'https://logo.clearbit.com/nvidia.com' },
    ],
    history: generateHistory(25, 1.5),
  },
  {
    id: '9',
    ticker: 'DBX0AN',
    name: 'Xtrackers II Overnight Rate Swap',
    type: 'Bonds',
    provider: 'Xtrackers',
    price: 142.10,
    change: 0.01,
    aum: '€8.2B',
    ter: 0.10,
    isin: 'LU0290358497',
    domicile: 'Luxembourg',
    replication: 'Synthetic',
    distribution: 'Accumulating',
    riskScale: 1,
    holdings: [
      { name: 'ECB Cash', weight: '100%', logo: 'https://logo.clearbit.com/ecb.europa.eu' },
    ],
    history: generateHistory(141, 0.05),
  },
  {
    id: '10',
    ticker: 'INRG',
    name: 'iShares Global Clean Energy',
    type: 'ESG',
    provider: 'iShares',
    price: 12.45,
    change: -1.82,
    aum: '€3.2B',
    ter: 0.65,
    isin: 'IE00B1XNHC34',
    domicile: 'Ireland',
    replication: 'Physical (Sampling)',
    distribution: 'Distributing',
    riskScale: 7,
    holdings: [
      { name: 'First Solar', weight: '8.2%', logo: 'https://logo.clearbit.com/firstsolar.com' },
    ],
    history: generateHistory(15, 0.8),
  }
];
